#!/bin/bash

#Second task
IFS=':' read -r -a array <<< "$PATH"
for i in "${!array[@]}"
do
	if [[ ${array[$i]} == $1 ]]; then
	 	echo "Request found"
	fi
done

#Third task
export MYPATH="/home/rima/Downloads"
if [[ $1 == "file" ]]; then
	echo `ls -p $MYPATH | grep -v /`
elif [[ $1 == "directory" ]]; then
	echo `ls $MYPATH`
fi
