#!/bin/bash

#$1 is first argument (env name)
#$2 is the second argument (file or dir)

#gives back dirs || files under path
if [[ $2 == "dir" ]]
then
	ls -d $1/*/
elif [[ $2 == "file" ]]
then
	ls -f $1/
else
	echo "Typed wrong type"
fi
